from constants import *
from strategy import *

turnoverExit = Strategy(name = "Turnover and exit", 
                        long = Policy.down_cross_indicator, 
                        exLong = Policy.propagate,
                        short = Policy.up_cross_indicator, 
                        exShort = Policy.propagate,
                        enter_on_next = True,
                        modes = [MODE_ALL, MODE_LONGS, MODE_SHORTS], 
                        long_params = {'prices': 'close',
                                       'indicator': Indicator.sma, 
                                       'ret_val': SIGNAL_LONG,
                                       'window': 30}, 
                        exLong_params = {'ret_val': SIGNAL_EXIT,
                                         'window': 4},
                        short_params = {'prices': 'close',
                                        'indicator': Indicator.sma, 
                                        'ret_val': SIGNAL_SHORT,
                                        'window': 30}, 
                        exShort_params = {'ret_val': SIGNAL_EXIT,
                                          'window': 4})

turnoverStrat = Strategy(name = "Simple turnover", 
                        long = Policy.down_cross_indicator, 
                        exLong = Policy.up_cross_indicator, 
                        short = Policy.up_cross_indicator, 
                        exShort = Policy.down_cross_indicator, 
                        modes = [MODE_ALL, MODE_LONGS, MODE_SHORTS], 
                        long_params = {'prices': 'close',
                                       'indicator': Indicator.sma, 
                                       'ret_val': SIGNAL_LONG,
                                       'window': 100}, 
                        exLong_params = {'prices': 'close',
                                         'indicator': Indicator.sma, 
                                         'ret_val': SIGNAL_EXIT,
                                         'window': 100},
                       short_params = {'prices': 'close',
                                       'indicator': Indicator.sma, 
                                       'ret_val': SIGNAL_SHORT,
                                       'window': 100}, 
                        exShort_params = {'prices': 'close',
                                         'indicator': Indicator.sma, 
                                         'ret_val': SIGNAL_EXIT,
                                         'window': 100})

turnoverExitRange = Strategy(name = "Turnover and exit", 
                        long = Policy.down_cross_indicator, 
                        exLong = Policy.propagate,
                        short = Policy.up_cross_indicator, 
                        exShort = Policy.propagate,
                        enter_on_next = True,
                        modes = [MODE_ALL, MODE_LONGS, MODE_SHORTS], 
                        long_params = {'prices': ['close', 'open'],
                                       'indicator': Indicator.sma, 
                                       'ret_val': SIGNAL_LONG,
                                       'window': range(15, 46, 3),
                                       'defaults': {'window':30}}, 
                        exLong_params = {'ret_val': SIGNAL_EXIT,
                                         'window': range(3, 7),
                                         'defaults': {'window':4}},
                        short_params = {'prices': 'close',
                                        'indicator': Indicator.sma, 
                                        'ret_val': SIGNAL_SHORT,
                                        'window': 30}, 
                        exShort_params = {'ret_val': SIGNAL_EXIT,
                                          'window': 4})

turnoverStratRange = Strategy(name = "Simple turnover", 
                        long = Policy.down_cross_indicator, 
                        exLong = Policy.up_cross_indicator, 
                        short = Policy.up_cross_indicator, 
                        exShort = Policy.down_cross_indicator, 
                        modes = [MODE_ALL, MODE_LONGS, MODE_SHORTS], 
                        long_params = {'prices': 'close',
                                       'indicator': Indicator.sma, 
                                       'ret_val': SIGNAL_LONG,
                                       'window': range(15, 46, 3),
                                       'defaults': {'window':30}}, 
                        exLong_params = {'prices': 'close',
                                         'indicator': Indicator.sma, 
                                         'ret_val': SIGNAL_EXIT,
                                         'window': range(15, 46, 3),
                                         'defaults': {'window':30}},
                       short_params = {'prices': 'close',
                                       'indicator': Indicator.sma, 
                                       'ret_val': SIGNAL_SHORT,
                                       'window': range(15, 46, 3),
                                       'defaults': {'window':30}}, 
                        exShort_params = {'prices': 'close',
                                         'indicator': Indicator.sma, 
                                         'ret_val': SIGNAL_EXIT,
                                         'window': range(15, 46, 3),
                                         'defaults': {'window':30}})